name: 'stock_pulse'
version: '1.0.0'
config-version: 2

profile: 'stock_pulse'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  stock_pulse:
    +materialized: view
    staging:
      +schema: stockpulse_staging
    intermediate:
      +schema: stockpulse_staging
    marts:
      +schema: stockpulse_marts

seeds:
  stock_pulse:
    industry_code_mapping:
      +column_types:
        industry_code: string