stock_pulse:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /app/secrets/gcp-sa-key.json
      project: stock-pulse-260629
      dataset: stockpulse_staging
      threads: 4
      location: us-west1